### ISSUE TITLE
If stop share it reverts all inputs shared too, even if input has been changed.

### ISSUE THREAD

**Issue by xuther** [byuoitav/touchpanel-ui-microservice#283]
### Steps to Replicate

Pi 1 shares to 2
Pi 3 shares to 2 (or 2 changes input)
Pi 1 stops sharing
Pi 2 will revert to default input

## Expected 
Pi 2 is unaffected by the change.

**Comment by xuther** [comment]
My guess is that we need to listen for input events for the devices I'm sharing to - if I get an input for one that is in my list of 'controlled devices' that takes it's input out of lock with what I'm doing - it removes it from the list. If we get one that comes back - we get back on the share list? Something like this?

**Comment by dannyrandall** [comment]
This was fixed by #292 (Or sometime around there). If a user changes input/stops mirroring the master panel of its group, that panel will remove it from the list of panels it is controlling and therefore won't change its input when the master is done sharing. If a user leaves a group, they can later rejoin the group and mirror the master panel again.
